# Generated by Django 6.0.4 on 2026-05-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_stock', models.PositiveIntegerField(default=0)),
                ('added_stock', models.PositiveIntegerField(default=0)),
                ('sold_stock', models.PositiveIntegerField(default=0)),
                ('remaining_stock', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'ordering': ['product__name'],
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
