# Generated by Django 6.0.4 on 2026-05-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Bartender', 'Bartender'), ('Waiter', 'Waiter')], default='Waiter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shift_time', models.CharField(default='08:00 - 17:00', max_length=50)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branches.branch')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
